project_id = "basketmatch"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://127.0.0.1:3000",
  "http://127.0.0.1:3000/auth/callback",
  "http://localhost:3000/auth/callback",
  "basketmatch://**",
  "exp://127.0.0.1:8081",
  "exp://127.0.0.1:8081/**",
  "exp://localhost:8081",
  "exp://localhost:8081/**",
]
enable_signup = true
